[package]
name = "scribble"
version = "0.1.0"
authors = ["≈Åukasz Adamczak <lukasz@czak.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
